# SnapRecon Configuration Example
# Copy this file to config.toml and modify as needed

[gemini]
model = "gemini-1.5-flash"
max_cost_usd = 10.0

[browser]
user_agent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
timeout_ms = 30000
fullpage = false

[discovery]
subfinder_bin = "subfinder"
concurrency = 5

[runtime]
scan_profile = "balanced"  # fast, balanced, or full
dry_run = false

[wappalyzer]
enabled = false
scan_type = "balanced"  # fast, balanced, full
threads = 3

[output]
output_dir = "runs"
verbose = true
availability_check_enabled = true
